# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fantuan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
