# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fantuan2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo1', models.CharField(max_length=500)),
                ('desh1', models.CharField(max_length=50)),
                ('price1', models.IntegerField()),
                ('photo2', models.CharField(max_length=500)),
                ('desh2', models.CharField(max_length=50)),
                ('price2', models.IntegerField()),
                ('photo3', models.CharField(max_length=500)),
                ('desh3', models.CharField(max_length=50)),
                ('price3', models.IntegerField()),
                ('photo4', models.CharField(max_length=500)),
                ('desh4', models.CharField(max_length=50)),
                ('price4', models.IntegerField()),
            ],
        ),
    ]
