# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftapp', '0002_fantuan2'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
